const menuOptions = [
  {
    name: "Dev Junior",
    price: 35.99,
    category: "dev",
    vegan: false,
    src: "./assets/dev-junior2.jpg",
  },
  {
    name: "Dev Bacon",
    price: 40.75,
    category: "dev",
    vegan: false,
    src: "./assets/dev-bacon.jpg",
  },
  {
    name: "Dev Vegano",
    price: 42.50,
    category: "dev",
    vegan: true,
    src: "./assets/dev-vegano.jpg",
  },
  {
    name: "Dev Smash",
    price: 50.75,
    category: "dev",
    vegan: false,
    src: "./assets/dev-smash2.jpg",
  },
  {
    name: "Dev Senior",
    price: 53.99,
    category: "dev",
    vegan: false,
    src: "./assets/dev-senior2.jpg",
  },
  {
    name: "X-Salada",
    price: 25.99,
    category: "simple",
    vegan: false,
    src: "./assets/xbacon.png",
  },
  {
    name: "X-Bacon",
    price: 29.50,
    category: "simple",
    vegan: false,
    src: "./assets/bacon-egg.png",
  },
  {
    name: "X-Vegano",
    price: 30.75,
    category: "simple",
    vegan: true,
    src: "./assets/xvegan.png",
  },
  {
    name: "X-Tudo",
    price: 32.99,
    category: "simple",
    vegan: false,
    src: "./assets/monstruoso.png",
  },
  {
    name: "Big Vegano",
    price: 37.5,
    category: "simple",
    vegan: true,
    src: "./assets/monstruoso-vegan.png",
  },
];